docs: fix typos
GradienceTeam/Gradience pull request #646
Opened 2022-11-05 01:40 UTC by kianmeng

Found via `codespell -S po,builddir`.

Let me know if you want additional Codespell CI job added https://github.com/GradienceTeam/Gradience/tree/main/.github/workflows.

2022-11-05 12:47 UTC, tfuxu requested changes

2022-11-05 12:47 UTC, tfuxu commented on .github/workflows/translation.yml
> +          committer: "Gradience Bot"
This should be left as-is for now, because of a typo in: https://github.com/GradienceTeam/action-update-pot/blob/22d1a5035552d86817f2b86401d62c0b4d8fda23/action.yml#L26

2022-11-05 12:48 UTC, tfuxu commented on gradience/main.py
> +                Adw.Toast(title=_("Preset reset")))
Not related to PR, but we should use here instead of a `reset` some different word.

2022-11-05 13:11 UTC, tfuxu approved these changes

2022-11-05 13:12 UTC, daudix-UFO approved these changes

2022-11-05 13:12 UTC, merged

2022-11-05 13:13 UTC, tfuxu commented
Okay, I think we can merge this. Thanks for a PR @kianmeng :)

2022-11-06 02:30 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: