Improve GNOME HIG compliance
GradienceTeam/Gradience pull request #648
Opened 2022-11-10 03:49 UTC by TheEvilSkeleton

Global description

This improves UX by allowing users to close through dialogs by pressing Esc. I added mnemonics for the file picker, and set `save` as the default response.

## Changelog

- Allow Esc shortcut to close dialogs
- Add mnemonics for dialogs
- Set `save` as default response

## Screenshot

If applicable

2022-11-10 03:57 UTC, TheEvilSkeleton commented
How can I test this? Whenever I build it locally with GNOME Builder, I get this error:
```
Application started at 10:56:58 PM
bwrap: execvp gradience: Permission denied
Application exited
```

2022-11-10 12:40 UTC, tfuxu commented
@TheEvilSkeleton 
Check that: https://discourse.gnome.org/t/what-causes-bwrap-execvp-my-app-name-permission-denied-flatpack/10540

2022-11-10 21:16 UTC, daudix-UFO commented
> How can I test this? Whenever I build it locally with GNOME Builder, I get this error:
> 
> ```
> Application started at 10:56:58 PM
> bwrap: execvp gradience: Permission denied
> Application exited
> ```

Sorry, this is my fault, everything fixed now 😅

2022-11-10 21:20 UTC, tfuxu commented
Oh now I see, it was because of incorrect access modes. I was wondering for five minutes why I can't run local.sh when I checkout to this PR 😂️

2022-11-10 21:21 UTC, daudix-UFO commented
_*Daudix was messing around with new IDE (Kate)_

2022-11-10 21:40 UTC, tfuxu requested changes
Overall great additions, but you still can add those improvements to other dialogs. As a example, you can add `ShortcutController` to presets manager. This is just a suggestion, so if you don't want to do that, then just resolve my comment in `window.blp`, and then we will merge your PR.

2022-11-10 21:40 UTC, tfuxu commented on data/ui/window.blp
> +
We probably shouldn't add `Esc` as a shortcut to close main window. None of the Gtk apps I've checked does this.

2022-11-10 21:45 UTC, daudix-UFO commented on data/ui/window.blp
> +
Yup, all windows close by global shortcut `Control + Q`, so app don't need one

2022-11-10 21:48 UTC, TheEvilSkeleton commented on data/ui/window.blp
> +
> We probably shouldn't add `Esc` as a shortcut to close main window. None of the Gtk apps I've checked does this.

I drafted it because I rushed and didn't look twice at what I was changing. I did not mean to do that x)

That being said, I am going to add the shortcut in other windows too.

2022-11-10 23:44 UTC, TheEvilSkeleton commented
I made some changes:
- Plugin rows look cleaner (and placed correctly) ![image](https://user-images.githubusercontent.com/50847364/201228917-95830406-12bc-4fb4-8394-df83be78b0fe.png)
- File picker is now modal and sticks with the parent window
- Gradience can be closed with Ctrl+Q
- Presets Manager can be closed with Esc

2022-11-11 13:35 UTC, tfuxu commented
> Tested those changes and seems like everything works as expected, can we remove Draft status?

Not yet, maybe they want to add something more. There are still mnemonics missing in most of the dialogs.

2022-11-11 13:35 UTC, daudix-UFO commented
Ah, OK

2022-11-11 20:17 UTC, TheEvilSkeleton commented
I reworded from "Favourite(s)" to "Favorite(s)" for consistency, since it's already using "Color(s)". If you want, I can revert it back or work with something else.

2022-11-11 20:20 UTC, daudix-UFO commented
I like it!

2022-11-11 20:31 UTC, TheEvilSkeleton commented on data/ui/window.blp
>              label: _("Apply");
I'm not sure why but I can't set a mnemonic for this. Same with Presets Manager window.

2022-11-11 20:46 UTC, 0xMRTT approved these changes
LGTM, except that I don't understand why there is a `_` in button in all gnome apps I saw.

2022-11-11 20:47 UTC, TheEvilSkeleton commented
`_` is a mnemonic. If you see e.g. `_M`, it means the user can trigger that button by pressing Alt+M.

2022-11-11 20:49 UTC, 0xMRTT commented
Thanks 👍 for the explanation

2022-11-11 20:49 UTC, daudix-UFO approved these changes
LGTM too 👍

2022-11-11 20:49 UTC, tfuxu commented
> I reworded from "Favourite(s)" to "Favorite(s)" for consistency, since it's already using "Color(s)". If you want, I can revert it back or work with something else.

It should be good, as UI text is now mostly written in American English (I think we had it before in British English).
PS. Please name future commits with something more than just "e". It doesn't look good in commit history.

2022-11-11 20:51 UTC, tfuxu commented on data/ui/window.blp
>              label: _("Apply");
For those buttons you don't set mnemonics, it is for option buttons in message boxes.

2022-11-11 20:51 UTC, 0xMRTT commented
Yeah, we should add pre commit or something for linting and formatting before pushing

2022-11-11 20:52 UTC, daudix-UFO commented
Squash and merge?

2022-11-11 20:53 UTC, tfuxu commented on data/ui/window.blp
>              label: _("Apply");
Just like you set in "Save preset as..." dialog.

2022-11-11 20:53 UTC, tfuxu commented
> Squash and merge?

We could do that

2022-11-11 20:54 UTC, 0xMRTT commented
Omg, I miss clicked

2022-11-11 20:54 UTC, TheEvilSkeleton commented
> > I reworded from "Favourite(s)" to "Favorite(s)" for consistency, since it's already using "Color(s)". If you want, I can revert it back or work with something else.
> 
> It should be good, as UI text is now mostly written in American English (I think we had it before in British English). PS. Please name future commits with something more than just "e". It doesn't look good in commit history.

FYI you can squash and merge commits.

2022-11-11 20:54 UTC, 0xMRTT commented
https://pre-commit.com/ ?

2022-11-11 21:02 UTC, tfuxu commented
> FYI you can squash and merge commits, so I don't think it's a big deal. Otherwise, I can rebase and force push if that's what you prefer.

Nah, we'll just squash it. Are you still going to add mnemonics, or is that everything?

2022-11-11 21:03 UTC, TheEvilSkeleton commented
No, I can't figure it out so it'd be better if they can be added later.

2022-11-11 21:03 UTC, 0xMRTT commented
So, is it okay for everyone? 

If yes, squash and merge

2022-11-11 21:04 UTC, tfuxu commented
Okay

2022-11-11 21:04 UTC, tfuxu approved these changes

2022-11-11 21:04 UTC, merged

2022-11-11 21:05 UTC, 0xMRTT commented
Thanks @TheEvilSkeleton  for this contribution 🚀