misc: compose various jobs into one CI job
GradienceTeam/Gradience pull request #700
Opened 2023-01-13 12:45 UTC by daudix-UFO

# Description

Combine various GH Actions jobs into one nice job, translation and pysa are separated

## Type of change

- [ ] Bugfix (Change which fixes a issue)
- [ ] New feature (Change which adds new functionality)
- [x] Enhancement (Change which slightly improves existing code)
- [ ] Breaking change (This change will introduce incompatibility with existing functionality)

## Changelog 

- Compose a few jobs into one

## Testing

- [x] I have tested my changes and verified that they work as expected 

### How to test the changes

No information provided.

2023-01-13 15:24 UTC, 0xMRTT approved these changes
LGTM, but why the CI is failing ? @daudix-UFO

2023-01-13 16:02 UTC, daudix-UFO commented
Really? Flatpak/checks run successfully I think

2023-01-15 23:25 UTC, tfuxu requested changes
Well, I don't agree with most of the changes made in this PR, but it shouldn't be that much hustle to fix it (also looking through my review, flatpak workflow probably should need to stay with name `Build`).

2023-01-15 23:25 UTC, tfuxu commented on .github/workflows/ci.yml
> +  analyze:
I don't really see the purpose of CodeQL in this project.

2023-01-15 23:25 UTC, tfuxu commented on .github/workflows/ci.yml
> +  typos:
I would move `typos` job to a separate workflow if it makes a whole workflow fail when it detects a typo, and I think it should be only done in pull requests, because the same as `Dependency Review` job, it would be redundant to run it on every push.

2023-01-15 23:25 UTC, tfuxu commented on .github/workflows/greetings.yml
> -# Change the look of Adwaita, with ease
I think that not everything must have a specific purpose here to exist. It's just cool to have a workflow that welcomes our first-time contributors.

2023-01-15 23:36 UTC, daudix-UFO commented
Alright, I agree with this, will change all this soon

2023-01-17 19:55 UTC, tfuxu requested changes
@daudix-UFO
Current workflow file fails with a syntax error: https://github.com/GradienceTeam/Gradience/actions/runs/3941328119
That's because one workflow file can't hold multiple `on` statements, as this is interpreted in YAML as a `duplicated mapping key` error.

2023-01-17 20:04 UTC, daudix-UFO commented
Ah, ok

2023-01-17 20:55 UTC, daudix-UFO commented
_this PR now makes no sense :<_

2023-01-17 22:41 UTC, tfuxu commented
I think it makes slightly more sense now :)

2023-01-17 22:47 UTC, tfuxu approved these changes

2023-01-18 00:04 UTC, merged