Proofreading
GradienceTeam/Gradience pull request #785
Opened 2023-06-19 23:32 UTC by salarua

## Description

Improves and clarifies wording in various areas of the UI

## Type of change

- [x] Bugfix (Change which fixes a issue)
- [ ] New feature (Change which adds new functionality)
- [ ] Enhancement (Change which slightly improves existing code)
- [ ] Breaking change (This change will introduce incompatibility with existing functionality)

## Testing

- [x] I have tested my changes and verified that they work as expected 

### How to test the changes

No information provided.

2023-06-19 23:41 UTC, daudix-UFO commented
Well I don't agree with some of them, will review tomorrow, today is too late

2023-06-20 12:29 UTC, tfuxu requested changes
Most of the proofreading here looks good to me. For those with which I don't fully agree, I provided comments and change suggestions below.

2023-06-20 12:29 UTC, tfuxu commented on data/ui/monet_theming_group.blp
> +  description: _("Monet Engine generates a color palette from an image.");
```suggestion
  description: _("Monet Engine generates a Material Design 3 color palette from an image.");
```
Material Design 3 should be left in the description, to clarify that this engine exclusively generates only MT3 palettes, as there are other tools that can generate different color palettes from an image (like `pywal`).

2023-06-20 12:32 UTC, daudix-UFO commented on data/ui/help_overlay.blp
This text were taken from GNOME clocks, so maybe we should keep it?

2023-06-20 12:34 UTC, daudix-UFO commented on data/ui/shell_prefs_window.blp
Perhaps shell should start with capital S

2023-06-20 12:35 UTC, daudix-UFO commented on data/ui/welcome_window.blp
> -                                description: _("Change the look of Adwaita, with ease");
Sounded better before

2023-06-20 12:36 UTC, daudix-UFO commented on data/ui/welcome_window.blp
> -                            description: _("Change colors of windows, buttons, lists and more, with advanced features like adding custom CSS.");
I haven't seen such pattern in any GNOME core or circle app

2023-06-20 16:09 UTC, salarua commented on data/ui/preset_row.blp
> +    subtitle: _("This preset has no description.");  // maybe it's better to just say (no description)
that's true. i was thinking it could be like a basic placeholder that's obvious it's a placeholder, but "This preset has no description." is a bit nicer

2023-06-20 16:13 UTC, salarua commented on data/ui/monet_theming_group.blp
> +  description: _("Monet Engine generates a color palette from an image.");
i rewrote that description with a non-technically inclined user in mind, but seeing as this entire application isn't ready for primetime yet, i'd be comfortable specifying that it's an MD3 palette.

2023-06-20 16:21 UTC, salarua commented on data/ui/help_overlay.blp
yeah, let's keep it if there's precedent in a Core application.

2023-06-20 16:30 UTC, tfuxu approved these changes

2023-06-20 16:33 UTC, daudix-UFO approved these changes

2023-06-20 16:33 UTC, tfuxu commented
Can we merge?

2023-06-20 16:34 UTC, salarua commented on data/ui/welcome_window.blp
> -                                description: _("Change the look of Adwaita, with ease");
it's bad style to separate a preposition in a simple sentence like that. if it were more complicated, a comma would be needed to prevent potential confusion; but since it's a pretty simple sentence it just looks odd.

2023-06-20 16:34 UTC, merged